name: DevSecOps pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # 1. VARREDURA DE SEGREDOS (TruffleHog)
  secrets-scanning:
    name: Secrets Scanning (TruffleHog)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog-oss-action@main
        with:
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified

  # 2. ANÁLISE DE DEPENDÊNCIAS (SCA com Trivy)
  sca-scanning:
    name: Dependency Scanning (Trivy SCA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

  # 3. ANÁLISE ESTÁTICA (SAST com Semgrep)
  sast-scanning:
    name: Static Code Analysis (Semgrep SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          docker run --rm -v "${PWD}:/src" returntocorp/semgrep semgrep scan --config=auto --error --severity=HIGH --severity=CRITICAL
