# Generated by Django 6.0.5 on 2026-05-24 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('tipo', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico')], default='paciente', max_length=10, verbose_name='Tipo de usuário')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('otp_ativo', models.BooleanField(default=False, verbose_name='2FA ativo')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'db_table': 'perfil_usuario',
            },
        ),
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_email', models.EmailField(max_length=254, verbose_name='E-mail tentado')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP de origem')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso?')),
                ('motivo_falha', models.CharField(blank=True, choices=[('senha_incorreta', 'Senha incorreta'), ('2fa_invalido', '2FA inválido'), ('conta_bloqueada', 'Conta bloqueada'), ('sessao_expirada', 'Sessão expirada')], max_length=100, verbose_name='Motivo da falha')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'db_table': 'tentativa_login',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='tentativa_l_ip_addr_daa467_idx'), models.Index(fields=['usuario_email', 'timestamp'], name='tentativa_l_usuario_638d92_idx')],
            },
        ),
    ]
