# Generated by Django 6.0.5 on 2026-05-24 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consentimento', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('versao_termo', models.CharField(default='1.0', max_length=10, verbose_name='Versão do Termo')),
                ('consentiu', models.BooleanField(default=True, verbose_name='Consentiu?')),
                ('data_consentimento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Consentimento')),
                ('data_revogacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Revogação')),
                ('ip_consentimento', models.GenericIPAddressField(verbose_name='IP do Consentimento')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('finalidade', models.CharField(default='Agendamento de consultas médicas e comunicação com o paciente.', max_length=200, verbose_name='Finalidade')),
            ],
            options={
                'verbose_name': 'Consentimento LGPD',
                'verbose_name_plural': 'Consentimentos LGPD',
                'db_table': 'consentimento_lgpd',
            },
        ),
    ]
