# Generated by Django 6.0.5 on 2026-05-24 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('LOGIN_OK', 'Login bem-sucedido'), ('LOGIN_FALHA', 'Falha de login'), ('LOGIN_2FA', 'Autenticação 2FA'), ('LOGOUT', 'Logout'), ('CADASTRO', 'Cadastro'), ('RECUPERACAO_SENHA', 'Recuperação de senha'), ('LGPD_EXPORTACAO', 'Exportação de dados LGPD'), ('LGPD_EXCLUSAO', 'Exclusão de dados LGPD'), ('AGENDAMENTO', 'Agendamento'), ('BRUTE_FORCE', 'Tentativa de força bruta'), ('SESSAO_EXPIRADA', 'Sessão expirada')], max_length=30, verbose_name='Tipo')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'log_auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tipo_evento', 'timestamp'], name='log_auditor_tipo_ev_a5d1f3_idx'), models.Index(fields=['usuario', 'timestamp'], name='log_auditor_usuario_25d921_idx')],
            },
        ),
    ]
